/** @format */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import DashboardSidebar from "@/components/CommonComponents/DashboardSidebar";
import NavBar from "@/components/CommonComponents/NavBar";
import Providers from "@/redux/Providers";
import { Bounce, ToastContainer } from "react-toastify";
import GoogleOAuthProvider from "@/components/AuthComponents/GoogleOAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const googleClientId =
    process.env.GOOGLE_CLIENT_ID || process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
        suppressHydrationWarning
      >
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
        <GoogleOAuthProvider clientId={googleClientId}>
          <Providers>
            <SidebarProvider>
              <DashboardSidebar />
              <SidebarInset className="overflow-x-hidden">
                <div className="min-h-screen w-full bg-[#F2F7FF]  ">
                  <NavBar />
                  {children}
                </div>
              </SidebarInset>
            </SidebarProvider>
          </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
